import { Router } from 'express';
import healthRoutes from './health.routes';
import authRoutes from './auth.routes';
import businessProfileRoutes from './businessProfile.routes';
import farmerRoutes from './farmer.routes';
import cropRoutes from './crop.routes';
import staffRoutes from './staff.routes';
import buyerRoutes from './buyer.routes';
import cropPriceRoutes from './cropPrice.routes';
import purchaseRoutes from './purchase.routes';
import weighingRecordRoutes from './weighingRecord.routes';
import staffAssignmentRoutes from './staffAssignment.routes';
import staffPaymentRoutes from './staffPayment.routes';
import transporterRoutes from './transporter.routes';
import driverRoutes from './driver.routes';
import vehicleRoutes from './vehicle.routes';
import transportRecordRoutes from './transportRecord.routes';
import inventoryRoutes from './inventory.routes';
import saleRoutes from './sale.routes';
import qualityStatusRoutes from './qualityStatus.routes';
import qualityRecordRoutes from './qualityRecord.routes';
import saleSettlementRoutes from './saleSettlement.routes';
import buyerPaymentRoutes from './buyerPayment.routes';
import transportPaymentRoutes from './transportPayment.routes';
import expenseCategoryRoutes from './expenseCategory.routes';
import expenseRoutes from './expense.routes';
import profitLossRoutes from './profitLoss.routes';
import documentRoutes from './document.routes';
import dashboardRoutes from './dashboard.routes';
import reportRoutes from './report.routes';
import auditRoutes from './audit.routes';
import alertRoutes from './alert.routes';
import userRoutes from './user.routes';
import staffEntryRoutes from './staffEntry.routes';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/business-profile', businessProfileRoutes);
router.use('/farmers', farmerRoutes);
router.use('/crops', cropRoutes);
router.use('/staff', staffRoutes);
router.use('/buyers', buyerRoutes);
router.use('/crop-prices', cropPriceRoutes);
router.use('/purchases', purchaseRoutes);
router.use('/weighing-records', weighingRecordRoutes);
router.use('/staff-assignments', staffAssignmentRoutes);
router.use('/staff-payments', staffPaymentRoutes);
router.use('/transporters', transporterRoutes);
router.use('/drivers', driverRoutes);
router.use('/vehicles', vehicleRoutes);
router.use('/transport-records', transportRecordRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/sales', saleRoutes);
router.use('/quality-statuses', qualityStatusRoutes);
router.use('/quality-records', qualityRecordRoutes);
router.use('/sale-settlements', saleSettlementRoutes);
router.use('/buyer-payments', buyerPaymentRoutes);
router.use('/transport-payments', transportPaymentRoutes);
router.use('/expense-categories', expenseCategoryRoutes);
router.use('/expenses', expenseRoutes);
router.use('/profit-loss', profitLossRoutes);
router.use('/documents', documentRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/reports', reportRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/alerts', alertRoutes);
router.use('/users', userRoutes);
router.use('/staff-entries', staffEntryRoutes);

// Future module routes will be mounted here.

export default router;
